---
- name: Start of the playbook
  hosts: build_host
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: ~/Documents/simple-test/project2021-main/testarAnsible
        state: directory
        owner: andrere
        group: axusers
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: ~/Documents/simple-test/project2021-main/testarAnsible/Dockerfile
        owner: andrere
        group: axusers
        mode: '0644'
    - name: build container image
      docker_image:
        name: hello_container:v1.0
        build:
          path: ~/Documents/simple-test/project2021-main/testarAnsible
        source: build
        
- name: Save container
  hosts: build_host
  gather_facts: no
  tasks:
    - name: archive container image as a tarball
      docker_image:
        name: hello_container:v1.0
        archive_path: ~/Documents/simple-test/project2021-main/testarAnsible/hello_container_v1_0.tar
        source: pull
        state: present
    - name: fetch archived image
      fetch:
        src: ~/Documents/simple-test/project2021-main/testarAnsible/hello_container_v1_0.tar
        dest: ./hello_container_v1_0.tar
        flat: true

- name: load play
  hosts: build_host
  gather_facts: no

  tasks:
     - name: copy tarball to host
       copy:
        src: ./hello_container_v1_0.tar
        dest: ~/Documents/simple-test/project2021-main/testarAnsible/hello_container_v1_0.tar

     - name: load container from tarball
       docker_image:
        force_source: true
        name: hello_container:v1.0
        load_path: ~/Documents/simple-test/project2021-main/testarAnsible/hello_container_v1_0.tar
        state: present
        source: load

     - name: Start docker program in terminal
       docker_container:
        detach: false        
        name: hello_container_v1.0.tar
       register: hello_container_output

     - name: Show string in terminal
       debug:
        var: hello_container_output